### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by sandeemanda** [google/sa360-webquery-bigquery#10]
Hi,
I have followed step-by-step instructions mentioned in the video but unfortunately I am getting the following error mentioned below. Can you please help me with this?

Exception in thread "main" java.lang.NullPointerException
        at dswebquerytobigquery.Authorizer.refreshAndStoreCredential(Authorizer.java:58)
        at dswebquerytobigquery.Authorizer.authorize(Authorizer.java:51)
        at dswebquerytobigquery.Main.main(Main.java:45)

Thanks for your help in advance!

**Comment by anantdamle** [comment]
@sandeemanda thanks for bringing this up again. This was a regression bug caused in [PR#7](https://github.com/google/sa360-webquery-bigquery/pull/7/files?file-filters%5B%5D=#diff-6e3bdcf86a63a1c737c9e2ae815b3441)

@JiandongWu thanks for [Issue#3](https://github.com/google/sa360-webquery-bigquery/issues/3) The issue seems to be completely fixed, thanks for your patience.

Next steps
1. Issue command `rm -rf datastore/` to clear any old credentials
2. Follow the command to recompile `mvn clean compile assembly:single`
3. Use the new `.jar` file

**Comment by sandeemanda** [comment]
Thanks a lot @anantdamle, its working now!
